version: 2
jobs: 
  build: 
    docker: 
    - image: node:12.16.2

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache depandencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache of no exact match is found
        - v1-dependencies-

    - run: yarn install

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    # run tests!
    - run: yarn test

    - run: yarn build

    - run: yarn netlify:deploy