export const SET_STATE_TOOLS_DATA = "SET_STATE_TOOLS_DATA";
export const SET_STATE_SORTED_INFO = "SET_STATE_SORTED_INFO";
export const SET_STATE_FILTERED_TOOLS_DATA = "SET_STATE_FILTERED_TOOLS_DATA";
export const SET_STATE_QUERY = "SET_STATE_QUERY";